#ifndef RASTEREFFECTSINCLUDE_H
#define RASTEREFFECTSINCLUDE_H

#include "blureffect.h"
#include "shadoweffect.h"
#include "motionblureffect.h"
#include "wipeeffect.h"
#include "noisefadeeffect.h"
#include "colorizeeffect.h"
#include "brightnesscontrasteffect.h"
#include "vignetteeffect.h"
#include "chromaticaberrationeffect.h"
#include "letterboxeffect.h"
#include "scanlineseffect.h"
#include "gloweffect.h"
#include "directionalblureffect.h"
#include "radialblureffect.h"
#include "wavewarpeffect.h"
#include "raineffect.h"
#include "edgedetecteffect.h"
#include "inverteffect.h"
#include "tinteffect.h"
#include "pixelateeffect.h"
#include "noiseeffect.h"
#include "mirroreffect.h"
#include "glitcheffect.h"
#include "posterizeeffect.h"
#include "twirleffect.h"
#include "channelblureffect.h"
#include "halftoneeffect.h"
#include "shakeeffect.h"
#include "dropshadoweffect.h"
#include "zoomblureffect.h"
#include "colorgradingeffect.h"
#include "stripeeffect.h"
#include "motiontileeffect.h"

#endif // RASTEREFFECTSINCLUDE_H
